.TH GT 1 "2021 April 8" "0.0.1"

.SH NAME
gt - Ghost Trick: Phantom Detective, a public domain source code reproduction of the original Ghost Trick: Phantom Detective.

.SH SYNOPSIS
.B gt
[options] [savefile.sav]

.SH DESCRIPTION
gt is widely incomplete. The main intentions of gt is to make it easier to create modifications to the game and make it possible to be ported to other platforms.

.SH OPTIONS

.SH BUGS
To report bugs, create a new issue here https://github.com/fmlatghor/gt/issues.

.SH AUTHORS
Ghost Trick: Phantom Detective was originally developed at Capcom, lead by Shu Takumi. Though this project is entirely the work of fm'latghor <fm@fmlatghor.com>.

.SH COPYRIGHT
The source code for gt is licensed under the Unlicense, while the documentation is licensed under the Creative Commons Zero v1.0 Universal (CC0) license. For more information, see the "LICENSES" directory included with this project.
