#!/bin/dash
SCRIPTS="./scripts"
NLZSS="$SCRIPTS/nlzss"

for d in data/st*/; do ( cd "${d}" && for file in *.xml.lz; do ../../$NLZSS/nlzss "$file" > "${file%.*}"; done ); done

# for d in data/st*/; do
# 	( cd "${d}" && for file in *.xml.lz; do
# 		../../$NLZSS/nlzss "$file" > "${file%.*}" &
# 		pid=$!
# 		wait $pid
# 	done);
# done

# find data/st*/*.xml.lz -type f \( -name "*game*" -o -name "*demo*" -o -name "*chapter*" \) |
# 	while read file; do
# 		nlzss $file > ${file%.*}; #&
# 		# pid=$!
# 		# wait $pid
# 	done
