#!/bin/zsh
cd ../..
ndstool -x baserom.nds -d data
for d in data/st*/; do ( cd "${d}" && for file in *.xml.lz; do nlzss "${file}" > "${file%.*}"; done ); done
./scripts/SDATTool/__main__.py -o -u data/sound_data.sdat assets/sound_data
