#!/bin/zsh
SCRIPTS="./scripts"
NLZSS="$SCRIPTS/nlzss"
TREADER="$SCRIPTS/ghost-treader"

for d in data/st*/; do ( $TREADER/encode.py $d && cd "$d" && for file in *.xml.lz; do $NLZSS/nlzss-c "$file" > "$file.lz"; done ); done
